version: 0.2
env:
  variables:
    IMAGE_NAME: 'tn-ecr'
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo ${IMAGE_NAME}
      - $(aws ecr get-login --no-include-email --region ${aws_region})
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - URI=${AWS_ACCOUNT_ID}.dkr.ecr.${aws_region}.amazonaws.com/${IMAGE_NAME}
      - echo $URI
  build:
    commands:
      - docker build -t $URI:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker push $URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - printf '{"Version":"1.0","ImageURI":"%s"}' $URI:$CODEBUILD_RESOLVED_SOURCE_VERSION > imageDetail.json
artifacts:
  files: 
    - imageDetail.json
    - appspec.yaml
    - service.json